import './styles.css';
const KEY='race-line-os-v1';
const initial={profile:{name:'Ashrith',futureRole:'Formula 1 Vehicle Dynamics Engineer',position:'Class 11 PCM'},tasks:[],sessions:[],projects:[],skills:[],settings:{xpPerHour:60,xpPerQuestion:2}};
let state=load(), page='Dashboard', charts=[]; const $=s=>document.querySelector(s); const today=()=>new Date().toISOString().slice(0,10); const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY))}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state)); render()}
function stats(){const sessionXP=state.sessions.reduce((a,x)=>a+(+x.duration||0)*state.settings.xpPerHour/60+(+x.questions||0)*state.settings.xpPerQuestion,0); const taskXP=state.tasks.filter(t=>t.done).reduce((a,t)=>a+(+t.xp||0),0); const skillXP=state.skills.reduce((a,k)=>a+(+k.xp||0),0); const xp=Math.round(sessionXP+taskXP+skillXP), level=Math.floor(xp/1000)+1; const hours=state.sessions.reduce((a,x)=>a+(+x.duration||0)/60,0), questions=state.sessions.reduce((a,x)=>a+(+x.questions||0),0); const dates=[...new Set(state.sessions.map(x=>x.date).concat(state.tasks.filter(t=>t.doneAt).map(t=>t.doneAt)))]; let streak=0,d=new Date(today()); while(dates.includes(d.toISOString().slice(0,10))){streak++;d.setDate(d.getDate()-1)} return {xp,level,hours,questions,streak,total:state.tasks.length,done:state.tasks.filter(t=>t.done).length,progress:state.tasks.length?Math.round(state.tasks.filter(t=>t.done).length/state.tasks.length*100):0}}
function render(){charts.forEach(c=>c.destroy()); charts=[]; $('#app').innerHTML=`<div class="app"><aside><h1>🏎 Race Line</h1>${['Dashboard','Pit Stop','Study Sessions','Projects','Skills','Roadmap','Knowledge','Achievements','Settings'].map(n=>`<button class="nav ${page===n?'active':''}" data-page="${n}">${icon(n)}${n}</button>`).join('')}</aside><main>${view()}</main></div>`; document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()}); bind(); drawCharts()}
function icon(n){return {Dashboard:'📊','Pit Stop':'🏁','Study Sessions':'📚',Projects:'🛠️',Skills:'🌳',Roadmap:'🎓',Knowledge:'🧠',Achievements:'🏆',Settings:'⚙️'}[n]}
function view(){return {Dashboard:dashboard, 'Pit Stop':tasks, 'Study Sessions':sessions, Projects:projects, Skills:skills, Roadmap:roadmap, Knowledge:knowledge, Achievements:achievements, Settings:settings}[page]()}
function dashboard(){const s=stats();return `<header><p>GOOD MORNING ${esc(state.profile.name).toUpperCase()}</p><h2>${esc(state.profile.futureRole)}</h2><span>📍 ${esc(state.profile.position)}</span></header><div class="grid"><section class="card"><h3>Today's Pit Stop</h3><b>${s.progress}%</b><progress value="${s.progress}" max="100"></progress></section><section class="card"><h3>Current Streak</h3><b>🔥 ${s.streak}</b><p>days</p></section><section class="card"><h3>Engineering XP</h3><b>Level ${s.level}</b><p>${s.xp} XP</p></section><section class="card"><h3>Live Stats</h3><p>${s.hours.toFixed(1)} hours studied</p><p>${s.questions} questions solved</p></section><section class="card wide"><h3>AI Race Engineer</h3><p>Good morning, ${esc(state.profile.name)}. ${s.total?`${s.done}/${s.total} pit-stop tasks are complete.`:'No tasks loaded. Create your first mission to start collecting real XP.'} Current level: ${s.level}.</p></section>${chartCard()}</div>`}
function chartCard(){return `<section class="card wide"><h3>Live Telemetry</h3><div class="charts"><canvas id="studyChart"></canvas><canvas id="questionsChart"></canvas><canvas id="projectChart"></canvas><canvas id="skillChart"></canvas></div></section>`}
function tasks(){return `<header class="top"><h2>Task Engine</h2><button id="addTask">+ New Task</button></header><div class="toolbar">${['daily','weekly','monthly'].map(c=>`<button data-reset="${c}">Reset ${c}</button>`).join('')}</div>${state.tasks.sort((a,b)=>a.order-b.order).map((t,i)=>`<div class="row task" draggable="true" data-index="${i}" data-id="${t.id}"><input type="checkbox" data-field="done" ${t.done?'checked':''}><input data-field="title" value="${esc(t.title)}"><select data-field="cadence"><option ${t.cadence==='daily'?'selected':''}>daily</option><option ${t.cadence==='weekly'?'selected':''}>weekly</option><option ${t.cadence==='monthly'?'selected':''}>monthly</option></select><input type="number" data-field="xp" value="${t.xp}"><button data-del-task="${t.id}">🗑️</button></div>`).join('')}`}
function sessions(){return `<header class="top"><h2>Study Sessions</h2><button id="saveSession">Save Session</button></header><div class="form"><input id="subject" placeholder="Subject"><input id="topic" placeholder="Topic"><input id="duration" type="number" placeholder="Duration minutes"><input id="questions" type="number" placeholder="Questions Solved"><input id="notes" placeholder="Notes"></div>${state.sessions.map(s=>`<div class="row"><b>${esc(s.subject)||'Untitled'}</b><span>${esc(s.topic)}</span><span>${s.duration} min</span><span>${s.questions} q</span><button data-del-session="${s.id}">🗑️</button></div>`).join('')}`}
function projects(){return `<header class="top"><h2>Project Garage</h2><button id="addProject">Create Project</button></header><div class="grid">${state.projects.map(p=>{let pc=p.items.length?Math.round(p.items.filter(i=>i.done).length/p.items.length*100):0;return `<section class="card"><input data-project="${p.id}" data-field="name" value="${esc(p.name)}"><progress value="${pc}" max="100"></progress><p>${pc}% complete</p><input type="date" data-project="${p.id}" data-field="deadline" value="${p.deadline||''}"><select data-project="${p.id}" data-field="priority"><option ${p.priority==='Low'?'selected':''}>Low</option><option ${p.priority==='Medium'?'selected':''}>Medium</option><option ${p.priority==='High'?'selected':''}>High</option></select><textarea data-project="${p.id}" data-field="notes" placeholder="Notes">${esc(p.notes||'')}</textarea>${p.items.map(i=>`<p class="check"><input type="checkbox" data-item="${p.id}:${i.id}" ${i.done?'checked':''}><input data-item-text="${p.id}:${i.id}" value="${esc(i.text)}"><button data-del-item="${p.id}:${i.id}">×</button></p>`).join('')}<button data-add-item="${p.id}">Add checklist</button><button data-del-project="${p.id}">Delete</button></section>`}).join('')}</div>`}
function skills(){return `<header class="top"><h2>Engineering Skill Tree</h2><button id="addSkill">Add Skill</button></header>${state.skills.map(k=>`<div class="row"><input data-skill="${k.id}" data-field="name" value="${esc(k.name)}"><input data-skill="${k.id}" data-field="category" value="${esc(k.category)}"><input type="number" data-skill="${k.id}" data-field="xp" value="${k.xp}"><progress value="${k.xp}" max="${k.target}"></progress><button data-del-skill="${k.id}">🗑️</button></div>`).join('')}`}
function roadmap(){return `<section class="card wide"><h2>College Roadmap</h2><p>Create roadmap milestones as projects and tasks. Progress stays zero until stored data exists.</p></section>`}
function knowledge(){return `<section class="card wide"><h2>Knowledge Hub</h2><p>Use study sessions, project notes, and skills to build a real resource system from your own data.</p></section>`}
function achievements(){const s=stats(), list=[['First Study Session',state.sessions.length>0],['100 Questions Solved',s.questions>=100],['First Project',state.projects.length>0],['Level 5 Engineer',s.level>=5]]; return `<h2>Achievements</h2>${list.map(a=>`<div class="achievement ${a[1]?'on':''}">🏆 ${a[0]} ${a[1]?'✅':''}</div>`).join('')}`}
function settings(){return `<h2>Settings</h2><div class="form"><input data-profile="name" value="${esc(state.profile.name)}"><input data-profile="futureRole" value="${esc(state.profile.futureRole)}"><input data-profile="position" value="${esc(state.profile.position)}"><input type="number" data-setting="xpPerHour" value="${state.settings.xpPerHour}"><input type="number" data-setting="xpPerQuestion" value="${state.settings.xpPerQuestion}"></div>`}
function bind(){document.body.onclick=e=>{let id=e.target.id,d=e.target.dataset;if(id==='addTask'){state.tasks.push({id:uid(),title:'New Mission',cadence:'daily',xp:25,done:false,doneAt:null,order:state.tasks.length});save()} if(d.reset){state.tasks=state.tasks.map(t=>t.cadence===d.reset?{...t,done:false,doneAt:null}:t);save()} if(d.delTask){state.tasks=state.tasks.filter(t=>t.id!==d.delTask);save()} if(id==='saveSession'){state.sessions.push({id:uid(),date:today(),subject:$('#subject').value,topic:$('#topic').value,duration:+$('#duration').value||0,questions:+$('#questions').value||0,notes:$('#notes').value});save()} if(d.delSession){state.sessions=state.sessions.filter(s=>s.id!==d.delSession);save()} if(id==='addProject'){state.projects.push({id:uid(),name:'New Project',deadline:'',priority:'Medium',notes:'',items:[]});save()} if(d.addItem){state.projects.find(p=>p.id===d.addItem).items.push({id:uid(),text:'',done:false});save()} if(d.delProject){state.projects=state.projects.filter(p=>p.id!==d.delProject);save()} if(d.delItem){let [p,i]=d.delItem.split(':');let pr=state.projects.find(x=>x.id===p);pr.items=pr.items.filter(x=>x.id!==i);save()} if(id==='addSkill'){state.skills.push({id:uid(),name:'New Skill',category:'Engineering',xp:0,target:1000});save()} if(d.delSkill){state.skills=state.skills.filter(k=>k.id!==d.delSkill);save()}}; document.body.oninput=e=>updateField(e); document.body.onchange=e=>updateField(e); let drag=null; document.querySelectorAll('.task').forEach(el=>{el.ondragstart=()=>drag=+el.dataset.index; el.ondragover=ev=>ev.preventDefault(); el.ondrop=()=>{let arr=state.tasks.sort((a,b)=>a.order-b.order),[m]=arr.splice(drag,1);arr.splice(+el.dataset.index,0,m);state.tasks=arr.map((t,i)=>({...t,order:i}));save()}})}
function updateField(e){let d=e.target.dataset,v=e.target.type==='checkbox'?e.target.checked:e.target.value;if(d.field&&e.target.closest('.task')){let t=state.tasks.find(x=>x.id===e.target.closest('.task').dataset.id);t[d.field]=d.field==='xp'?+v:v;if(d.field==='done')t.doneAt=v?today():null;save()} if(d.project){state.projects.find(p=>p.id===d.project)[d.field]=v;save()} if(d.item){let [p,i]=d.item.split(':');state.projects.find(x=>x.id===p).items.find(x=>x.id===i).done=v;save()} if(d.itemText){let [p,i]=d.itemText.split(':');state.projects.find(x=>x.id===p).items.find(x=>x.id===i).text=v;save()} if(d.skill){state.skills.find(k=>k.id===d.skill)[d.field]=d.field==='xp'?+v:v;save()} if(d.profile){state.profile[d.profile]=v;save()} if(d.setting){state.settings[d.setting]=+v;save()}}
function drawCharts(){if(!$('#studyChart')||!window.Chart)return; const days=[...Array(7)].map((_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);return d.toISOString().slice(5,10)}); const by=(fn)=>days.map(lbl=>state.sessions.filter(s=>s.date.slice(5,10)===lbl).reduce(fn,0)); charts.push(new Chart($('#studyChart'),{type:'bar',data:{labels:days,datasets:[{label:'Weekly Study Hours',data:by((a,s)=>a+(+s.duration||0)/60),backgroundColor:'#ff8700'}]}})); charts.push(new Chart($('#questionsChart'),{type:'line',data:{labels:days,datasets:[{label:'Questions Solved',data:by((a,s)=>a+(+s.questions||0)),borderColor:'#00ff9d'}]}})); charts.push(new Chart($('#projectChart'),{type:'doughnut',data:{labels:state.projects.map(p=>p.name),datasets:[{label:'Project Progress',data:state.projects.map(p=>p.items.length?Math.round(p.items.filter(i=>i.done).length/p.items.length*100):0),backgroundColor:['#ff8700','#00ff9d','#37a2ff','#f43f5e']}]}})); charts.push(new Chart($('#skillChart'),{type:'radar',data:{labels:state.skills.map(s=>s.name),datasets:[{label:'Skill Progress',data:state.skills.map(s=>Math.min(100,Math.round((+s.xp||0)/(+s.target||1000)*100))),borderColor:'#ff8700'}]}}))}
function esc(x){return String(x??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
render();
